### ISSUE TITLE
[Design]: Text format in a client information tab

### ISSUE THREAD

**Issue by christiehenderson** [LamplightCRM/feedback#404]
### Does this relate to any of our high-level objectives?

- [ ] Continuity: is was hard for an existing user to figure this out...
- [ ] Accessible: this aspect was inaccessible or hard to use
- [ ] Works on all devices: this could be improved on a particular device

### Which of DUAPER does this relate to?

- [ ] Discoverable - you can't find the thing you're looking for / expecting
- [ ] Understandable - this doesn't make sense in this context
- [ ] Affordances - I didn't realise it's a control I could interact with
- [ ] Predictable - I was surprised not in a good way
- [ ] Efficient - too many clicks or other interactions
- [ ] Responsive - there was no feedback about what's going on

### Please provide more details

Would it be possible to swap the font from BOLD on the question to normal and the ANSWERS (data entered) in BOLD so that they stand out. This would help with accessibility. It is mainly on the Client information tab that is is an issue for our administrators.

**Comment by mattparker** [comment]
Hi,

Yes it'd be possible with some custom CSS. I think it's something we'll need to do with you so you can see the changes and check you're happy with them - could you add a question in the help pages referencing this issue so someone can book some time to do this with you on your system?

The basic CSS will be 

```css

[role="tabpanel"] {
    & .widgetdata {
        .vi-data-label {
            font-weight: 400;
        }
        :is(dd, .detaildata) * {
            font-weight: bold;
        }
    }
}
```

but there may need to be various tweaks, depending.
