### ISSUE TITLE
[Design]: Visual readability feedback

### ISSUE THREAD

**Issue by B-Bearman** [LamplightCRM/feedback#478]
### Does this relate to any of our high-level objectives?

- [ ] Continuity: is was hard for an existing user to figure this out...
- [ ] Accessible: this aspect was inaccessible or hard to use
- [ ] Works on all devices: this could be improved on a particular device

### Which of DUAPER does this relate to?

- [x] Discoverable - you can't find the thing you're looking for / expecting
- [ ] Understandable - this doesn't make sense in this context
- [ ] Affordances - I didn't realise it's a control I could interact with
- [ ] Predictable - I was surprised not in a good way
- [x] Efficient - too many clicks or other interactions
- [ ] Responsive - there was no feedback about what's going on

### Please provide more details

We've had some feedback from staff about how quick and easy it is / is not for your eyes to find the info you're looking for on a page.

Firstly, they've noted that tables are improved as the alternate line shading helps to distinguish between different records. However, on profile tabs such as Personal, it is much more difficult to quickly find the info you're looking for than on the old version of LL.

On old, the data was to the right of the field name, so effectively it was laid out as if field name was in one column, and the data entered was in a separate column. However, on new, the data is underneath the field name. This means that the page is very long (needing lots of scrolling), with just one long list of field names and data, with no easy way to discern between the two. Granted, field names are in bold, but this isn't sufficient to distinguish them quickly and easily from the data entered.

If there is any way to improve this, that would be great - ideally to put the data entered to the right of the field name, but if that's not possible, then perhaps to shade behind every field name so that it's a bit easier for your eyes to differentiate between what is data and what is a field name.

If it helps to understand the issue better, staff have said that the screen for adding a new work record visually is much easier to navigate, but the Personal tab is one example where visually it is difficult.

Hope that makes sense!

Old Lamplight

![Image](https://github.com/user-attachments/assets/8c892534-a231-4276-8ee4-bc79eb8f722c)

New Lamplight

![Image](https://github.com/user-attachments/assets/33af247e-54f8-4189-9dd5-45dd3d344837)

### Do you have any suggestions to improve this?

See comment above.

**Comment by mattparker** [comment]
Thanks @B-Bearman for the feedback. I'm glad forms and tables are improved .

The UX research we've looked at suggests that linear layout is generally easier to use: if your eyes just have to go down the page that's easier than tracking left-to-right and down the page. That's especially true in Lamplight where we don't know in advance how long the text of labels or data is, so knowing how wide to make the columns - either you end up with big gaps between label and data, or longer labels get cramped up.

We can look at some custom CSS to change the formatting of labels in some or all tabs. @rbowsley it'd be something like 

```css
[role="tabpanel"] .widgetdata .vi-data-label {
    background-color: var(--bg-accent-1);
}
```

There was also discussion of adding some 'jump to' links in longer tabs that would use the captions within a tab - it's still on the 'later' list.

**Comment by B-Bearman** [comment]
Thanks for the considered response, @mattparker 

I understand. If we want to look at all of the info about a young person on a page, then I can appreciate it's easier only to have to track down.

In case it's helpful for another perspective... Our practitioners (counsellors, youth workers, advisers, etc) often only want to find one or two particular pieces of info about a young person amongst the data that has already been recorded on their Personal tab. Practitioners won't need to take in everything which is on there. To do that on old LL, their eyes tracked down until they found the correct label, and then across, but in new LL, they have to track and scroll down and mentally process a whole lot more info than previously until they get to the right label and data.

(Sorry, I'm not trying to be awkward, just wanted to explain our feedback a bit more!)

I realise you've given this a lot of thought already and so it's not likely to change in the system, so yes please, if we could have something like custom CSS to add shading to the background of labels, it would certainly help us and be much appreciated. @rbowsley if we could pick this up at some point, that'd be great.

Thanks again!

**Comment by mattparker** [comment]
Actually thinking about it it'd be possible to set some or all tabs to be left right with some custom CSS. I don't think you'd want the background color as well as the widths (and incidentally always better to use colours that use the var(--bg-accent-1) which will work in dark mode and across colour schemes).

%ages obviously can be varied according to taste.

```css 

[role="tabpanel"] .widgetdata {
    .vi-data-label {
        background-color: var(--bg-accent-1);
        width: 40%;
        display:inline-flex;
    }
   .vi-data-value {
        width: 60%;
        display:inline-flex;
   }
}
```

for a particular tab (ID 2)

```css
#tab_container_2[role="tabpanel"]  .widgetdata {
    .vi-data-label {
        background-color: var(--bg-accent-1);
        width: 40%;
        display:inline-flex;
    }
   .vi-data-value {
        width: 60%;
        display:inline-flex;
   }
}
```

I'll close this as an issue if that's OK though as it's not going to be something we want to change wholesale.
